BC001 TR01
buildingSMART/IFC4.x-IF pull request #36
Opened 2023-06-12 18:13 UTC by BenzclyZhang

2023-06-12 20:51 UTC, pjanck requested changes
Initial comments.

2023-06-12 20:51 UTC, pjanck commented on tests/TR01/Dataset/Reference_file/README.md
> +
I believe that there is a reference file now.

2023-06-12 20:51 UTC, pjanck commented on tests/TR01/Dataset/Reference_file/README.md
> +| BC001_Alignment(Reference).ifc    |    Data containing track alignments in IFC 4.3                                  |
Is this still up-to-date?

2023-06-12 22:01 UTC, BenzclyZhang commented on tests/TR01/Dataset/Reference_file/README.md
> +| BC001_Alignment(Reference).ifc    |    Data containing track alignments in IFC 4.3                                  |
Old file. Removed.

2023-06-13 14:45 UTC, pjanck commented on tests/TR01/README.md
> +  - EP002 - An `IfcElement` that composes another `IfcElement` shall not have `IfcRelPositions` relationship to an `IfcPositioningElement` or have `IfcRelContainedInSpatialStructure` relationship to
```suggestion
  - EP002 - An `IfcElement` that composes another `IfcElement` shall not have `IfcRelPositions` relationship to an `IfcPositioningElement` or have `IfcRelContainedInSpatialStructure` relationship to an `IfcSpatialStructureElement`.
```

2023-06-19 10:15 UTC, merged