Initial commit BC001 - BU01
buildingSMART/IFC4.x-IF pull request #37
Opened 2023-06-12 20:27 UTC by pjanck

- example file
- ids file
- documentation

2023-06-13 07:35 UTC, evandroAlfieri requested changes

2023-06-13 07:35 UTC, evandroAlfieri commented on tests/BU01/Dataset/README.md
what about adding the requirements for the property set + properties to the IDS? Something like
```
            <ids:applicability>
                <ids:entity>
                    <ids:name>
                        <ids:simpleValue>IFCBUILDING</ids:simpleValue>
                    </ids:name>
                </ids:entity>
            </ids:applicability>
            <ids:requirements>
                <ids:property measure="IFCLABEL">
                    <ids:propertySet>
                        <ids:simpleValue>SBB-CFF-FFS</ids:simpleValue>
                    </ids:propertySet>
                    <ids:name>
                        <ids:simpleValue>Status</ids:simpleValue>
                    </ids:name>
                </ids:property>
            </ids:requirements>
```
Or even going further constraining the values, where possible.

2023-06-13 14:34 UTC, pjanck commented on tests/BU01/Dataset/README.md
This is not a *requirement* of the test case (see [tests/BU01/readme.md](https://github.com/buildingSMART/IFC4.x-IF/pull/37/files#diff-d428a6592276c570f000550005913d5746d7602c8e57755a6de9bd4359c8cb39)). It is only a property of the provided reference dataset. The implementers are free to include it, however absence of these properties does not invalidate their dataset.

2023-06-14 15:09 UTC, evandroAlfieri approved these changes

2023-06-18 10:32 UTC, BenzclyZhang approved these changes

2023-06-19 09:27 UTC, evandroAlfieri commented
@BenzclyZhang just made a small PR for a quick change as branch to the rail repo. Please have a look and if it's ok update this PR, so I can merge. Thanks

2023-07-03 07:50 UTC, evandroAlfieri commented
> @BenzclyZhang just made a small PR for a quick change as branch to the rail repo. Please have a look and if it's ok update this PR, so I can merge. Thanks

Hi @BenzclyZhang, can you review and approve the small change I suggested - so that this test case can be published? Thanks
cc: @pjanck @apinzenoehler

2023-07-03 09:30 UTC, pjanck commented
> @BenzclyZhang just made a small PR for a quick change as branch to the rail repo

Simile to #38 - I can't seem to be able to find the PR. Can you please provide a link?

2023-07-03 09:38 UTC, evandroAlfieri commented
Forgot to PR from the patch branch, sorry. Here: https://github.com/bSI-RailwayRoom/IFC4.x-IF/pull/6

2023-07-12 07:58 UTC, pjanck commented
@evandroAlfieri This should be resolved now and ready for merging.

2023-07-12 08:36 UTC, merged