initial commit BC001 BU02 test plan
buildingSMART/IFC4.x-IF pull request #38
Opened 2023-06-18 20:37 UTC by pjanck

2023-06-18 20:38 UTC, pjanck commented
@BenzclyZhang please review as well.

2023-06-19 09:31 UTC, evandroAlfieri commented
same for BC01, @BenzclyZhang I did just a small change as a PR to the rail repo. Please have a look

2023-06-25 19:05 UTC, BenzclyZhang requested changes

2023-06-25 19:05 UTC, BenzclyZhang commented on tests/BU02/readme.md
> +The test plan builds upon the [TE01 test plan](../TE01/Readme.md).
```suggestion
The test plan builds upon the [AL01 test plan](../AL01/Readme.md).
```

2023-06-25 19:05 UTC, BenzclyZhang commented on tests/BU02/readme.md
> +!["Perspective view"](./Dataset/skewedview.PNG)
```suggestion
!["Perspective view"](./Dataset/skewedview.png)
```

2023-07-03 07:51 UTC, evandroAlfieri commented
> same for BC01, @BenzclyZhang I did just a small change as a PR to the rail repo. Please have a look

Hi @BenzclyZhang, can you review and approve the small change I suggested - so that this test case can be published? Thanks
cc: @pjanck @apinzenoehler

2023-07-03 09:29 UTC, pjanck commented
> same for BC01, @BenzclyZhang I did just a small change as a PR to the rail repo

I don't see a PR anywhere, but I believe I must be looking at the wrong place. Can you provide a link, please?

2023-07-03 09:37 UTC, evandroAlfieri commented
Forgot to PR from the patch branch, sorry. Here: https://github.com/bSI-RailwayRoom/IFC4.x-IF/pull/6

2023-07-09 08:49 UTC, BenzclyZhang approved these changes

2023-07-10 08:07 UTC, evandroAlfieri commented on tests/BU02/readme.md
> +    - https://github.com/buildingSMART/ifc-gherkin-rules/pull/65
See https://github.com/bSI-RailwayRoom/IFC4.x-IF/pull/7

2023-07-12 07:58 UTC, pjanck commented
@evandroAlfieri This should be resolved now and ready for merging.

2023-07-12 08:36 UTC, evandroAlfieri approved these changes

2023-07-12 08:37 UTC, merged