BC001 TE01 SierraSoft
buildingSMART/IFC4.x-IF pull request #81
Opened 2023-08-23 14:49 UTC by Massimiliano-SierraSoft

updated file

2023-08-24 07:49 UTC, evandroAlfieri approved these changes

2023-08-24 07:51 UTC, evandroAlfieri requested changes

2023-08-24 07:51 UTC, evandroAlfieri commented on SierraSoft/BC001_TE01_SierraSoft.zip
why is the file uploaded two times in different folders?

2023-08-29 10:57 UTC, apinzenoehler approved these changes
File is OK for detailed technical report and Domain review

2026-04-09 09:19 UTC, evandroAlfieri commented
This pull request is being closed as part of a broader repository cleanup effort.
Should this contribution be relevant in the future, it may be reopened and updated to ensure compliance with the latest official standard (IFC4.3 ADD2).

2026-04-09 09:19 UTC, closed without merging